### ISSUE TITLE
New section for toggle button on style guide

### ISSUE THREAD

**Issue by soniakaukonen** [trimble-oss/website-modus.trimble.com#654] opened 2023-07-19 14:48 UTC
https://github.com/trimble-oss/website-modus.trimble.com/issues/656 request.

Provide guidance for styling. Exists in Bootstrap.

**Comment by msankaran0712** [comment] 2023-07-20 05:58
@soniakaukonen I think this is a duplicate of https://github.com/trimble-oss/website-modus.trimble.com/issues/656

**Closed** 2023-07-20 08:09 UTC
